# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="dwmkerr"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  {% for plugin in ZSH_PLUGINS %}
    {{ plugin }}
  {% endfor %}
)

source $ZSH/oh-my-zsh.sh


# If the path_helper tool exists (i.e. on a Mac) then run it.
if [ -f "/usr/libexec/path_helper" ]; then
    eval $(/usr/libexec/path_helper -s)
fi

# Bash Completion.
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i


# ZSH auto-completion for kubernetes.
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi

# Load NVM.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Add support to the terminal for colours.
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export EDITOR=vim

# We're an xterm 256bit colour terminal, just in case anyone asks...
export TERM="xterm-256color"
alias tmux="tmux -2"

if [[ $COLORTERM = gnome-* && $TERM = xterm ]]  && infocmp gnome-256color >/dev/null 2>&1; then export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then export TERM=xterm-256color
fi

# Set some variables for prompt colours.
set_ps1 () {
    local darkgray="\e[0;30m"  # Dark Gray
    local darkgraybold="\e[1;30m" # Bold Dark Gray
    local red="\e[0;31m" # Red
    local redbold="\e[1;31m" # Bold Red
    local green="\e[0;32m" # Green
    local greenbold="\e[1;32m" # Bold Green
    local yellow="\e[0;33m" # Yellow
    local yellowbold="\e[1;33m" # Bold Yellow
    local blue="\e[0;34m" # Blue
    local bluebold="\e[1;34m" # Bold Blue
    local purple="\e[0;35m" # Purple
    local purplebold="\e[1;35m" # Bold Purple
    local turquoise="\e[0;36m" # Turquoise
    local turquoisebold="\e[1;36m" # Bold Turquoise
    local lightgray="\e[0;37m" # Light Gray
    local lightgraybold="\e[1;37m" # Bold Light Gray
    local bg_darkgray="\e[40m" # Dark Gray (Background)
    local bg_red="\e[41m" # Red (Background)
    local bg_green="\e[42m" # Green (Background)
    local bg_yellow="\e[43m" # Yellow (Background)
    local bg_blue="\e[44m" # Blue (Background)
    local bg_purple="\e[45m" # Purple (Background)
    local bg_turquoise="\e[46m" # Turquoise (Background)
    local bg_lightgray="\e[47m" # Light Gray (Background)

    # Setup the PS1 line if we are using bash.
    if [ -n "$BASH_VERSION" ]; then
        # Host, User, Working Directory
        export PS1="\[$(tput sgr0)\]\[\033[38;5;28m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;2m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]\n\\$ \[$(tput sgr0)\]"
    fi
}
set_ps1

# Set the language. This is required for some Python tools.
# Fix 'perl: warning: Setting locale failed.'
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# If we are not running in interactive mode, we're done.
[[ $- != *i* ]] && return

# We *are* interactive, so if we are not already in tmux, start it.
[[ -z "$TMUX" ]] && exec tmux

# Load auto-completions depending on our shell.
if [ -n "$BASH_VERSION" ]; then
    # Source auto-completions from the Mac and Linux locations.
    # Note that this is based on Bash Completion 2, which requires Bash 4 or onwards.
    export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
    [[ -r "/usr/local/etc/shell.d/bash_completion.sh" ]] && . "/usr/local/etc/shell.d/bash_completion.sh"
    if [ -f /etc/bash_completion ]; then . /etc/bash_completion; fi
elif [ -n "$ZSH_VERSION" ]; then
    # Source zsh auto-completions.
    fpath=($HOME/.zsh/completion $fpath)
    autoload -Uz compinit && compinit -i
fi

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh